# Generated by Django 2.1.2 on 2018-10-13 23:31

import actas.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(null=True, unique=True)),
                ('acta_pdf', models.ImageField(null=True, upload_to=actas.models.upload_image_path)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('creador', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=130, null=True)),
                ('apellidos', models.CharField(max_length=130, null=True)),
                ('ced_passport', models.PositiveIntegerField(null=True)),
                ('foto', models.ImageField(null=True, upload_to=actas.models.upload_image_path)),
                ('acta', models.ManyToManyField(to='actas.Acta')),
            ],
        ),
        migrations.CreateModel(
            name='Victimario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=130, null=True)),
                ('apellidos', models.CharField(max_length=130, null=True)),
                ('ced_passport', models.PositiveIntegerField(null=True)),
                ('foto', models.ImageField(null=True, upload_to=actas.models.upload_image_path)),
                ('acta', models.ManyToManyField(to='actas.Acta')),
            ],
        ),
    ]
