# Generated by Django 2.1.2 on 2018-10-14 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0003_auto_20181013_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acta',
            old_name='fecha',
            new_name='fecha_carga',
        ),
        migrations.RenameField(
            model_name='ciudadano',
            old_name='acta',
            new_name='actas',
        ),
        migrations.AddField(
            model_name='acta',
            name='encabezado',
            field=models.CharField(choices=[('sede 1', 'sede 1'), ('sede 2', 'sede 2')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='fecha_nac',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='motivo_inicio_proc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='victimario',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='victimario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='creador',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
