# Generated by Django 2.1.2 on 2018-10-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0005_auto_20181014_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='rol',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='victimario',
            name='ced_passport',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
