# Generated by Django 2.1.2 on 2018-10-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0006_auto_20181014_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='ced_passport',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
